version: '3.5'

networks:
  network-intra: 
    name: network-intra
    driver: bridge

services:
  testewweb:
    image: testewweb
    container_name: testewweb
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 256M
    ports:
        - 8080:8080
    environment:
        - TZ=America/Sao_Paulo
    networks:
        - network-intra