version: '3.8'

networks:
  network-intra: 
    name: network-intra
    driver: bridge

services:
  nginx:
    image: nginx:1.27.4
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/logs:/var/log/nginx
      # - ./nginx/certs:/etc/nginx/certs
    networks:
      - network-intra
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.19.4
    restart: unless-stopped
    ports:
      - 9000:9000
    mem_limit: 256M
    # to set admin password run the container below:
    #reference: https://gist.github.com/deviantony/62c009b41bde5e078b1a7de9f11f5e55
    #docker run --rm httpd:2.4-alpine htpasswd -nbB admin '@admin@admin' | cut -d ":" -f 2
    command: --admin-password '$$2y$$05$$O4LsQ5tQAT.0VxznwcZeWuL8KfsHmm0xGAvBj2S/0Kqucc3dApMSe'
    volumes:
      # - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - network-intra
  site1:
    image: site1
    container_name: site1
    build:
      context: ./site1
      dockerfile: Dockerfile
    mem_limit: 256M
    ports:
      - 8080:8080
    environment:
      - TZ=America/Sao_Paulo
      - BASE_PATH=/site1
    networks:
      - network-intra
   
