version: '3.8'

networks:
  network-intra: 
    name: network-intra
    driver: bridge

services:
  site1:
    image: site1
    container_name: site1
    build:
      context: ./TestWebApp
      dockerfile: Dockerfile
    mem_limit: 256M
    ports:
        - 8080:8080
    environment:
        - TZ=America/Sao_Paulo
    networks:
        - network-intra
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mapeando o nginx.conf
      # - ./nginx/conf.d:/etc/nginx/conf.d  # Mapeando o nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled  # Certifique-se que está apontando para o diretório correto
      # - ./nginx/certs:/etc/nginx/certs
      - ./nginx/logs:/var/log/nginx # Diretório de logs persistentes
    networks:
      - network-intra
   
